name: Upload Python Package

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Build release distributions
      run: |
        python -m pip install build
        python -m build

    - name: Upload distributions
      uses: actions/upload-artifact@v4
      with:
        name: release-dists
        path: dist/

  test-package:
    runs-on: ubuntu-latest

    needs:
      - build

    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/

      - name: Install the package
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install dist/*.whl

      - name: Run tests
        run: |
          source venv/bin/activate
          python -m unittest discover -s test
  
  pypi-publish:
    runs-on: ubuntu-latest

    needs:
      - test-package

    permissions:
      id-token: write

    environment:
      name: pypi
      url: https://pypi.org/p/aws-s3-helper

    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/

      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
